---
name: "deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
        - REPLACE_APP_NAME-helm-charts-stage
        - REPLACE_APP_NAME-helm-charts-prod

env:
  APP_NAME: poteapp
  MSVC_NAME: poteapp-accounts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
  
      - name: Get Latest Tag
        id: semantic_version
        run: echo "::set-output name=svtag::$(git tag --sort=committerdate | tail -1)"
      
      - run: |
          echo "promoting into ${{ github.event.inputs.environment }} environment!"
          git config --global user.email devopsify-bot@onekloud.io && git config --global user.name devopsify-bot
          echo "cloning config repo ${{ github.event.inputs.environment }}"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/$APP_NAME/${{ github.event.inputs.environment }}
          cd ${{ github.event.inputs.environment }}
          echo "checking out main branch"
          git checkout main
          echo "updating image tag: in Values.yaml file"
          sed -i "s,tag:.*,tag:\ ${{ steps.semantic_version.outputs.svtag }}," charts/$MSVC_NAME/values.yaml
          echo "updating version: in Chart.yaml file"
          sed -i "s,version:.*,version:\ ${{ steps.semantic_version.outputs.svtag }}," charts/$MSVC_NAME/Chart.yaml
          echo "updating appVersion: in Chart.yaml file"
          sed -i "s,appVersion:.*,appVersion:\ ${{ steps.semantic_version.outputs.svtag }}," charts/$MSVC_NAME/Chart.yaml
          git add . && git commit -m "updated image tag"
          git push
